# action.yml
name: 'gh-action-rl-scanner-only-dev'
author: 'ReversingLabs'
description: 'Scan an artifact with ReversingLabs secure.software CLI'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  artifact-to-scan:
    description: 'Path to the package file (artifact) you want to scan'
    required: true
    type: string
  report-path:
    description: 'Path to a directory where the reports will be saved (must be a new directory, with a path relative to the github.workspace)'
    required: false
    default: MyReportDir
    type: string
  rl-store:
    description: 'Path to a directory where a rl-store has been initialized'
    required: false
    default: ""
    type: string
  rl-diff-with:
    description: 'Perform a diff scan against the provided version'
    required: false
    default: ""
    type: string
  rl-package-url:
    description: 'A package url to use for this scan'
    required: false
    default: ""
    type: string
  rl-verbose:
    description: 'Make the scanner more verbose'
    required: false
    default: false
    type: bool
outputs:
  description:
    description: 'The result of the action: a string terminating in FAIL or PASS'
  status:
    description: 'The single word result of the action: success, failure or error'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: rl-scanner
      run: ${{ github.action_path }}/run-scanner.sh
      shell: bash
      env:
        REPORT_PATH: ${{ inputs.report-path }}
        MY_ARTIFACT_TO_SCAN_PATH: ${{ inputs.artifact-to-scan }}
        RL_STORE: ${{ inputs.rl-store}}
        RL_PACKAGE_URL: ${{ inputs.rl-package-url }}
        RL_DIFF_WITH: ${{ inputs.rl-diff-with }}
        RL_VERBOSE: ${{ inputs.rl-verbose }}

